runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  # APP_ENV: local
  APP_URL: https://speedball-215310.appspot.com
  APP_KEY: base64:LJHGztkR9/bjF9F6R39HfV5LDjwBuBrrwA5wJ5qk5WU=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  DB_HOST: 127.0.0.1
  DB_DATABASE: courier
  DB_USERNAME: root
  DB_PASSWORD: password
  DB_SOCKET: "/cloudsql/speedball-215310:asia-south1:courier"

  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: 587
  MAIL_USERNAME: jimlaravel@gmail.com
  MAIL_PASSWORD: dolphinsaver
  MAIL_ENCRYPTION: tls

  PUSHER_APP_ID: 463888
  PUSHER_APP_KEY: c0a8d7b1122459cd74c9
  PUSHER_APP_SECRET: 7b37777d9848ea0e1a8e
  PUSHER_APP_CLUSTER: ap2

  MIX_PUSHER_APP_KEY: "${c0a8d7b1122459cd74c9}"
  MIX_PUSHER_APP_CLUSTER: "${ap2}"

  FACEBOOK_CLIENT_ID: 166440594048523
  FACEBOOK_CLIENT_SECRET: 2eb8b756a7f34a0d65c6369ec258d231

  GOOGLE_CLIENT_ID: 59172636075-cbhims8uejrsuh0a22sp4aie36h29ok5.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: tcg21bE3EGYitrEL9svyMrel

  ALGOLIA_APP_ID: 5CLHLWKW21
  ALGOLIA_SECRET: d36aa0d003a38b503593b98acd8ce721


beta_settings:
  cloud_sql_instances: "speedball-215310:asia-south1:courier"
